DROP TABLE IF EXISTS `Keywords`;

CREATE TABLE `Keywords`
(
    ID INT NOT NULL PRIMARY KEY,
    `SiteID` INT NOT NULL,
    `Keyword` VARCHAR(100) NULL DEFAULT NULL,
    `KeywordMarket` VARCHAR(100) NULL DEFAULT NULL,
    `KeywordLocation` VARCHAR(100) NULL DEFAULT NULL,
    `KeywordDevice` VARCHAR(100) NULL DEFAULT NULL,
    `KeywordTranslation` VARCHAR(100) NULL DEFAULT NULL,
    `KeywordTags` VARCHAR(1000) NULL DEFAULT NULL,
    `GlobalSearchVolume` INT NULL DEFAULT 0,
    `RegionalSearchVolume` INT NULL DEFAULT 0,
    `CreatedAt` DATE
);

DROP TABLE IF EXISTS `KeywordRankings`;

CREATE TABLE `KeywordRankings`
(
    ID VARCHAR(100) NOT NULL UNIQUE,
    `SiteID` INT NOT NULL,
    `KeywordID` INT NOT NULL,
    `Rank` INT NULL DEFAULT 0,
    `BaseRank` INT NULL DEFAULT 0,
    `Url` VARCHAR(1000) NULL DEFAULT NULL,
    `date` DATE DEFAULT NULL,
    `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (ID)
);